### ISSUE TITLE
Login Page display issue when click on forget password link

### ISSUE THREAD

**Issue by ravian766** [enkodellc/blazorboilerplate#10]
On Login Page, click on "Forgot Password", button for forgot password does not display correctly.

![image](https://user-images.githubusercontent.com/13349419/61402297-3ebf8d80-a8ec-11e9-83f9-9846a7b5141b.png)

**Comment by enkodellc** [comment]
To clarify the issue, the page does not provide a page scrollbar when an expansion panel increases the size of the page causing content to below the screen and become inaccessible. 

This might be an issue with MatBlazor's  MatExpansion Panel. If you are using this in your app and feel that it is causing you issue. You have multiple options. First is to create a new page for "Forgot Password" so that the "Forgot Password" is just a link to that page and copy over the functionality. Second you could test out the MatExpansion panel and see if there is some CSS you could change to fix.  I will take a look at both solutions in the near future. For now you can choose either option for your project.

Thanks for submitting the issue. If you like you can submit a PR to BlazorBoilerplate or MatBlazor if you find a solution.
