### ISSUE TITLE
Exit from Login dialog

### ISSUE THREAD

**Issue by Oleg26Dev** [enkodellc/blazorboilerplate#139]
I am here https://blazorboilerplate.com/todo_list , then click Login, but do not want to Log in and want to exit and return to the todo_list page. But in the Login dialog is only button "Home". I think it may be good to close dialog and return to the previous page but not to Home always.

**Comment by enkodellc** [comment]
@Oleg26Dev thanks, I agree. This sounds like a good first PR for someone.

**Comment by soomon** [comment]
Why not use the back button of your browser?

**Comment by Oleg26Dev** [comment]
@soomon It can be quick solution but I think as a user. Login looks like modal dialog and have a button "Home".  I'd like to exit, I click Home because no other buttons.
May be button "<-" instead of Home. Keith know better ;-)

**Comment by enkodellc** [comment]
I agree that a return arrow  to return to the previous page. is a good idea. I don't know if there is any mechanism like asp.net's urlreferrer within Blazor. I am swamped with answering questions and other maintenance with BB.   I wish to gain more contributors so this should be a fairly simple task for someone's first PR! @Oleg26Dev  maybe you want to do some research and find if a solution is out there for this feature.  Another option might be to create a modal Dialog for Login instead of a page. Then exiting the login will just close the dialog and no need for a urlreferrer needed.

**Comment by win32nipuh** [comment]
@enkodellc  ok, I will check what can be done (as I see it ;-))

**Comment by enkodellc** [comment]
@win32nipuh, Great! One of the goal's of BB, maybe not spelled out is to get new contributors involved in features and solutions. It is definitely not for devs to make suggestions to me and and I solve if for them :)
