### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by KKacer** [enkodellc/blazorboilerplate#147]
Hello Keith,
I'm new to Blazor,
Wanted to use Serilog in the 'Component scope' inside the 'Common.UI' 
like the image below
https://imgur.com/a/keL8ImD

Serilog added to the package and added the import in the global scope of the project.
but the breakpoint not hit, and also it doesn't do logging.

probably the breakpoint can't be hit in the CSB, but the logging also won't happen.
another question of mine is how we can switch between CSB and SSB, seems all the time CSB runs.

**Comment by KKacer** [comment]
Aha seems Common.UI doesn't have Serilog, 
but still as a question how can we be able to do the logging as I expected in the posted screenshot? while we are at the component development phase.

**Comment by enkodellc** [comment]
@KKacer Thanks for using Blazor Boilerplate. These are very common newbie issues so I suggest that you start reading some more of the Blazor documentation for your ramp up. For debugging I suggest you use SSB as CSB is not easily debuggable yet. The best way to debug CSB is using Console.WriteLine(). 

I don't think you can use Serilog on Client side.. remember you have client that only has access to the local machine silo and not the server files. That is only accessible via API. Please review how Client / Server API"s work.

Instead of raising issues here your best bet is to get on the gitter and ask questions there that are not directly related to BB: https://gitter.im/aspnet/Blazor

Hope that helps and hope you stick with Blazor as it is awesome!
