### ISSUE TITLE
How to implement blazorboilerplate and keep it up to date with future changes?

### ISSUE THREAD

**Issue by tomRedox** [enkodellc/blazorboilerplate#159]
We've got an existing project where we've embedded server side Blazor (SSB) components onto Razor Pages and MVC pages.  I'm now looking to change that so the whole project is SSB and blazorboilerplate looks like the perfect starting point - I can't tell you what a relief finding this project is, I'm looking forward to getting involved.

Obviously blazorboilerplate is going to evolve over time, so if I just clone the repo and start adding to and modifying that code I'm going to make life difficult for myself when I then want to incorporate the changes from future versions of the blazorboilerplate repo back into my code (which I will no doubt need to if for no other reason than to stay up to date with the .net core versions).

Is there a good way to manage this?

**Comment by enkodellc** [comment]
@tomRedox Thanks, BB is evolving. There will be a major refactor in the next month or maybe 2. It is the "restructure" branch.  I try to do a good job of making releases so that should help with tracking.

As for keeping up to date I am not sure if I can give you the best opinion. My approach would be to watch the repo and each commit to see if it applies to your project. And of course be ready for major changes and see if they reflect your needs.  From what I can see our last major changes are going to be split the project up a bit more so that it is a bit more modular so you can more easily replace Auth / Storage if you want to do a different solution.  

I would suggest doing some google searching for options. @responsive-edge has been doing it so maybe he has something to offer. I do know he hasn't kept completely up to date but I think he watches and looks for fixes / nuget update changes and then updates his app accordingly.
