### ISSUE TITLE
Input validation for RegisterDto

### ISSUE THREAD

**Issue by justSteve** [enkodellc/blazorboilerplate#181]
In the RegisterDto class, the UserName field should add the following annotation to trigger an error when a user attempts a space char:
`[RegularExpression(@"[^\s]+", ErrorMessage = "Spaces are not permitted.")]`
        
While troubleshooting this issue I was initially distracted by the password/confirmPw validation taking place in Register.razor:
`if (registerParameters.Password != registerParameters.PasswordConfirm)`

That line is never triggered because of the annotation validation taking place in the Dto's definition. Is the redundant validation intentional?

**Comment by enkodellc** [comment]
Hi @justSteve -> Thanks Next time maybe you want to submit your first PR to Blazor Boilerplate?

1. Added. 

2. In Register.razor the line. Yes it is redundant at that point since there is client side validation on the form. The code was there most likely before the dto validation was in place. I will remove the code. Thanks.
