### ISSUE TITLE
how to use offline client?

### ISSUE THREAD

**Issue by drearyrainDeng** [enkodellc/blazorboilerplate#2]
is it possible to use sample function as offline client? thanks advance

**Comment by enkodellc** [comment]
Please clarify, maybe a link to what you are looking at. I am not sure if you are talking about the project as a whole or the Weather forecast data??

**Comment by drearyrainDeng** [comment]
i just do not sure  blazor client mode . as we debug service , the browser will load  framework and Component wasm, right?  how about .razor files?(after login, if i logout, it is not repsonse html content)  if all resources file be saved to local. it should use Weather function because depend on nothing.

**Comment by enkodellc** [comment]
Blazor Boilerplate is done in the Blazor Client Side Mode:  https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#blazor-client-side  

_The browser will load framework and Component wasm_. Yes I believe you are correct:

_If all resources file be saved to local:_ The database / SQL Lite for the IdentityServer / users is saved to the server.

_It should use Weather function because depend on nothing._ Weather function is calling the server API to retrieve the data so NO it is not local to the client. It is on the Blazor server that is created in the project.

I am still new to Blazor myself so please refer to Microsoft's documentation.

**Comment by drearyrainDeng** [comment]
as microsoft doc ,Blazor client design as SPA mode, so offline feature is major function.  i am newer too. IMO, it will push this project develop if support it  (if you want ),thank for you share

**Comment by enkodellc** [comment]
This blog seemed to have some good tips, a bit old. [https://gunnarpeipman.com/blazor/offline-blazor-application/](https://gunnarpeipman.com/blazor/offline-blazor-application/)

If your goal is a one-time download and run offline please share your tips and I will definitely be interested in seeing your fork. The changes would be good to have at least in another branch or commented in the main branch for others to review.

I will close this issue but feel free to continue the discussion here or in a PR.

**Comment by enkodellc** [comment]
Here is another possible resource: https://medium.com/@k.l.mueller/create-progressive-web-apps-with-net-using-blazor-6aa719e38000
