### ISSUE TITLE
Reset password button disabled

### ISSUE THREAD

**Issue by GioviQ** [enkodellc/blazorboilerplate#216]
Actually the condition is
`Disabled="@(UserRow.UserId != userProfile.UserId)"`

I think it should be the opposite.

**Comment by enkodellc** [comment]
@GioviQ - Are you referencing the Users List page?  My original intentions were to have only the user to have authorization to reset their own password.   It actually would be ideal to use the AuthorizationPolicyProvider and **Permissions.User.Update**  That would allow users to update their access on the UI. I think that only works in SSB right now.

**Comment by GioviQ** [comment]
The logged user can just change his own password in the profile section.
The admin user should be able to change password to all users. Not admin users do not have access to Users list page.
Do you agree?

**Comment by enkodellc** [comment]
The logged user can just change his own password in the profile section. - Understood
The admin user should be able to change password to all users - Yes but would like to not just be "admin" is the point I am try to make. Maybe the new roles will allow a different role with permissions to admin. 

So I think we can just remove the `Disabled="@(UserRow.UserId != userProfile.UserId)"`  completely now until more permissions are setup for CSB. 

Like I said this was originally done so that users could view the Users list but not edit. Now it is only Admin access.

**Comment by GioviQ** [comment]
I did not check permissions and differences between CSB and SSB, anyway in the future, only if the logged user is administrator, he should be able to reset password of all users, he can manage (I am thinking about tenants.).

**Comment by enkodellc** [comment]
@GioviQ if you want to submit a PR to change so admin can reset anyone's password I will merge it. I think the proper solution for it all is to test and apply more of the permissions to the UI. That is a slightly bigger project, but is needed. I appreciate all the questions and help!

**Comment by GioviQ** [comment]
At the moment I am completing Admin section for Clients and ApiResources, but I am going to try to learn more about tenant and permissions with supports of all contributors of this project.
