### ISSUE TITLE
Unable to find package Breeze.Sharp with version (>= 0.9.0)

### ISSUE THREAD

**Issue by Lasoty** [enkodellc/blazorboilerplate#344]
Error: NU1102	Unable to find package Breeze.Sharp with version (>= 0.9.0)
  - Found 29 version(s) in nuget.org [ Nearest version: 0.8.0 ]
  - Found 0 version(s) in https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
  - Found 0 version(s) in https://dotnet.myget.org/F/blazor-dev/api/v3/index.json	`BlazorBoilerplate.Server	C:\Users\lasot\source\repos\blazorboilerplate\src\Server\BlazorBoilerplate.Server\BlazorBoilerplate.Server.csproj	1`

**Comment by GioviQ** [comment]
It is here https://github.com/enkodellc/blazorboilerplate/tree/development/nupkg

You have to manually config Visual Studio with a new nuget origin pointing to your local path where nupkg folder is present.

The online version 0.8.0 has some bugs, so I fixed by myself as you can see in https://github.com/Breeze/breeze.sharp/pull/33
