### ISSUE TITLE
Exception when using SQLite because of nvarchar(max)

### ISSUE THREAD

**Issue by ktnr** [enkodellc/blazorboilerplate#469]
When using `"UseSqlLite": true,"` the following exception is thrown.

```
System.AggregateException: 'One or more errors occurred. (SQLite Error 1: 'near "max": syntax error'.)'

Inner Exception:
SqliteException: SQLite Error 1: 'near "max": syntax error'.

This exception was originally thrown at this call stack:
    [External Code]
    BlazorBoilerplate.Storage.DatabaseInitializer.MigrateAsync() in DatabaseInitializer.cs
    [External Code]
    BlazorBoilerplate.Storage.DatabaseInitializer.SeedAsync() in DatabaseInitializer.cs
```

Many of the database models have `.HasColumnType("nvarchar(max)")`. But SQLite does not support `varchar(max)` according to https://github.com/dotnet/efcore/issues/7030. This is one of the [limitations reported in the EF documentation](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations).

There is an [unresolved question on stackexchange](https://stackoverflow.com/questions/53560489/ef-core-sqlite-in-memory-exception-sqlite-error-1-near-max-syntax-error) regarding this topic. I did not manage to apply the suggested solution.

As a quick and dirty workaround one can replace every occurence with `nvarchar(max)` with `nvarchar(2048)`.

**Comment by GioviQ** [comment]
SQLite is not a db server and you discovered yourself this limitation too, so I think I will remove SQLite support.

**Comment by ktnr** [comment]
Your call. But SQLite is supported by EF, why remove it? Why has this something to with whether SQLite is a db server or not?

There surely is a solution to the `nvarchar(max)` problem. I don't know if there will be other points of friction...

**Comment by GioviQ** [comment]
A webapp should supoort thousands of concurrent users, with SQLite is not the case...

**Comment by EmergentCybernetics** [comment]
@GioviQ I ran into the same issue when trying to use PostgreSQL, which _is_ a server.

I'd like to be able to run this on PostgreSQL to make use of some other features we have in PostgreSQL. MS SQL has a hardcoded limit of requiring a server with 2GB or more of RAM, which is kind of a waste when PostgreSQL will easily run on a $5/month 1 core CPU and 1GB RAM server for our volume/load.

Being able to use SQLite is also nice for basic development. No need to setup a database server to get things running.

I'll be working on getting PostgreSQL supported again over the next month. Do you have any suggesting on how to handle this `nvarchar(max)` problem? PostgreSQL equivalent data type is `TEXT` or `VARCHAR` for `variable unlimited length`.
  * https://www.postgresqltutorial.com/postgresql-char-varchar-text/

I don't see `nvarchar(2048)` as being a solution because 2048 characters isn't always enough.

**Comment by maddadder** [comment]
Let me put this right here: https://github.com/justin2004/mssql_server_tiny

**Comment by GioviQ** [comment]
@EmergentCybernetics you could use the default MSSQLLocalDB
