### ISSUE TITLE
Client-side Auth Policies on Users Page not coming through on AuthorizeView

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#56]
I am running into Auth issues on the Users Page. I am busy with another project so if anyone finds out why it is not coming through please let me know.:

Client-side Auth Policies on Users Page not coming through on AuthorizeView. 

https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.Client/Pages/Admin/Users.razor
This might help: https://github.com/chrissainty/PolicyBasedAuthWithBlazor

**Comment by tstockwell** [comment]
I've only been looking at BBP for a couple of hours so I'm not going to post a PR :-).
BTW, I'm really impressed.

Anyway, the issue that I see with the Users page is that, when logged in as user, the call to api/Account/ListRoles fails with 401 (Unauthorized).  

![image](https://user-images.githubusercontent.com/2626063/68419625-38d20e80-0160-11ea-868a-c6ace704ada5.png)

This is due to Authorize attribute on BlazorBoilerplate.Server.Controllers.AccountController.ListRoles....

![image](https://user-images.githubusercontent.com/2626063/68419937-d0cff800-0160-11ea-98db-0ebb6aad5118.png)

Maybe that should just be [Authorize]?

**Comment by enkodellc** [comment]
I updated that this morning. Check the latest updates, not much but that was one of them. If you have fixes or other suggestions I gladly take PR's! thanks

**Comment by tstockwell** [comment]
I'm synced up with git now and I can't see a problem.  

Here's the Users page when I'm signed in as 'user'.  Note that the delete and edit icons are disabled and the RefreshPassword icon is enabled for the record associated with the current user.

![image](https://user-images.githubusercontent.com/2626063/68485962-cca9e600-0205-11ea-83a2-521d555606c7.png)


Here's the Users page when I'm signed in as admin, note that all actions are enabled except that the admin record can't be deleted.

![image](https://user-images.githubusercontent.com/2626063/68486256-5659b380-0206-11ea-99ae-938ee33fb5b1.png)

That all matches the AuthorizeViews on the Users page, so I think the code in Git is good.

**Comment by enkodellc** [comment]
Thanks for testing, Not sure what is going on with my system then. I get NO action buttons with user or admin.  I deleted my db.. maybe time to delete my VS cache and start from scratch.

**Comment by enkodellc** [comment]
It was my db connection localhost vs (localdb)\\MSSQLLocalDB. localhost works for my db connection best. Which blows my mind as I could log in and the rest of the db seemed to work. Just not the auth / permissions. Anyway fixed.

**Comment by tstockwell** [comment]
I had a similar issue when I fired up BBS for the first time yesterday.
What I didn't realize is that I have both Sql Server 2017 and Sql Server 2016 LocalDB installed.
localhost connects to Sql Server and localdb connects to Sql Server LocalDB.
