### ISSUE TITLE
VS 2022 Preview 4 / 4.1

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#682]
FYI I do not recommend using VS 2022 Preview 4 or 4.1. I have tried it on 2 different computers and it breaks BB pretty bad.

**Comment by scharada** [comment]
@enkodellc not sure if this is related but i do get the same error on both VS 2019 (latest update) and 2022 (latest preview)

![image](https://user-images.githubusercontent.com/1780858/140166931-56b52aeb-c25a-4c29-affb-2c5bcb63d2c9.png)

**Comment by enkodellc** [comment]
From my experience it is a visual studio bug... I think the best way I have solved this is closing VS. Manually deleting all obj and bin folders from the project, delete .vs folder. Microsoft has MANY bugs lately that have wasted hours of my time. NO code changes and it fails and many VS glitches with razor in VS 2022. I have pushed through but still a lot. Use VS2019 if you can.

**Comment by scharada** [comment]
@enkodellc thank you for responding. i'll give it a shot and comment back.
in the mean time, is there a doc on how to use the code generator ? the documentation does not cover that. thank you in advance.

**Comment by GioviQ** [comment]
@scharada please see https://blazor-boilerplate.readthedocs.io/en/latest/features/source_generators.html

**Comment by scharada** [comment]
@enkodellc here is an update. 

everything works when i set the server as the startup project in VS 2019. the client always fails. 
in VS 2022, it works when the startup project is the server and using the Kestrel profile only.

there is also an error that does not fail when compiling but is always there . here s a screenshot of it in the VS 2019 IDE (server project startup.cs line 710). the rror does not show in VS 2022.
![image](https://user-images.githubusercontent.com/1780858/140183157-90217959-6246-4af9-aff9-243205227943.png)

**Comment by scharada** [comment]
here is a more detailed error log from VS Code when running the client"

Cannot use file stream for [c:\repos\blazorboilerplate\src\Client\BlazorBoilerplate.Client\bin\Debug\net5.0\BlazorBoilerplate.Client.deps.json]: No such file or directory  
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'c:\repos\blazorboilerplate\src\Client\BlazorBoilerplate.Client\bin\Debug\net5.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'c:\repos\blazorboilerplate\src\Client\BlazorBoilerplate.Client\bin\Debug\net5.0\BlazorBoilerplate.Client.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'c:\repos\blazorboilerplate\src\Client\BlazorBoilerplate.Client\bin\Debug\net5.0\BlazorBoilerplate.Client.runtimeconfig.json' file and specify the appropriate framework.

**Comment by enkodellc** [comment]
https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found

**Comment by enkodellc** [comment]
VS 2022 still errors a lot for me... Anytime I edit a razor file it will show over a dozen "Feature XXX is currently unavailable due to an internal error.  When it does this a lot of VS features just stop working so you are basically left with a dumb text editor. VS team needs to figure this out.

It also will show a lot of TypeScript errors but still builds.  Not sure if it is my machine specific but these are quite frustrating issues.

![image](https://user-images.githubusercontent.com/2935721/142161478-44e76fc2-41f5-494e-80ca-a86290e7ec26.png)
