### ISSUE TITLE
Matblazor Error

### ISSUE THREAD

**Issue by marcoscavaleiro** [enkodellc/blazorboilerplate#7]
Hi, maybe this is an MatBlazor error.. but when i run the Blazor boilerplate i'm getting this error:

![image](https://user-images.githubusercontent.com/3036194/60611388-94e4ea80-9d9c-11e9-949b-82bf7cfcd8fb.png)

**Comment by enkodellc** [comment]
@marcoscavaleiro yes it is a known issue. I believe also a MatBlazor issue but have not really tracked down the root cause. Initially I thought it was a Tooltip so maybe you want to delete the tooltips and see if goes away. Let me know, otherwise it might be a few days before I get to tracking it down.

**Comment by marcoscavaleiro** [comment]
@enkodellc Thanks! I have removed the Tooltip and the error dissapear. 
I have debbuged and found one MatTooltip in MainLayout where the child element (an MatButton) dont have the attribute RefBack.. i put the attribute and the error dissapear. 
I will read better the RefBack doc in MatBlazor project

**Comment by marcoscavaleiro** [comment]
I have create an pull request to solve this error

**Comment by enkodellc** [comment]
Thanks @marcoscavaleiro I appreciate the PR. A simple error on my part. Hope you continue to use and contribute to BlazorBoilerplate.   There is a discussion on https://gitter.im/blazorboilerplate/community for projects that others users are doing to support and grow this open-source project.
