### ISSUE TITLE
Reload / resets Paging

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#746]
During a delete then reload this resets the paging to 0. I feel that is not expected behavior. @GioviQ  your thoughts? Maybe some new logic here to set the page to 0 or leave it??  Maybe something like this?

```
        protected async Task Reload(bool resetPaging = true)
        {
            if (resetPaging) table.CurrentPage = 0;
            await table.ReloadServerData();
        }
```

https://github.com/enkodellc/blazorboilerplate/blob/56756464fb7f90af5a3f29bc75c090d947091d50/src/Shared/Modules/BlazorBoilerplate.Theme.MudBlazor/Shared/Components/ItemsTableBase.cs#L115

**Comment by GioviQ** [comment]
There is not a single answer. It depends on the context. If there are concurrent operations of others users, staying on the same page after your and maybe others delete operations, it's not the case, because what you see it is a stale content and it is better you refresh all table, returning also on first page.
Even if you delete the only item of a page.

**Comment by GioviQ** [comment]
Anyway the resetPaging default should be false. When you change filter you have to reset page number.
